"""mars-weather-table-fix

Revision ID: 8a80ee3934e5
Revises: a2f139072239
Create Date: 2025-09-14 17:54:43.977210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a80ee3934e5'
down_revision: Union[str, Sequence[str], None] = 'a2f139072239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mars_weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sol', sa.Integer(), nullable=False),
    sa.Column('average_temperature', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_temperature', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_temperature', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('season', sa.String(length=100), nullable=True),
    sa.Column('month_ordinal', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mars_weather_id'), 'mars_weather', ['id'], unique=False)
    op.create_index(op.f('ix_mars_weather_max_temperature'), 'mars_weather', ['max_temperature'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mars_weather_max_temperature'), table_name='mars_weather')
    op.drop_index(op.f('ix_mars_weather_id'), table_name='mars_weather')
    op.drop_table('mars_weather')
    # ### end Alembic commands ###
