# Usar una imagen base de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY requirements.txt .
COPY main.py .
COPY mars_agent/ ./mars_agent/

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt


# Comando para iniciar la aplicación
CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]